# Taller de Metagenómica

Este taller de **LANDALAB** esta enfocado en la reconstrucción de genomas a partir de datos reales de metagenomas utilizando diferentes herramientas de software libre. Parte del taller reune información de [Data Carpentry.](https://carpentries-lab.github.io/metagenomics-analysis/)

**LANLAB:** Es un laboratorio a cargo de la Investigadora Mirna Vázquez-Rosas-Landa del Instituto de Ciencias del Mar y Limnología, UNAM.Enfocado en Metagenómica, Biología marina y programación y análisis de datos.

## Objetivos

El objetivo principal es capacitar a los participantes en la reconstrucción de genomas a partir del ensamblaje metagenómico con herramientas de softwares libres.

Los objetivos específicos son:

-Aprender los conceptos básicos y las herramientas principales en los análisis de datos metagenómicos.

-Fomentar el uso de estás nuevas técnicas en cuestiones ecológicas y médicas.

```{}
```

## Requisitos

-Acceso a una computadora,internet y una terminal

-Contar con Amazon Web Services (AWS) preconfigurado.

-Conocimientos básicos en bioinformática (Si apenas estas iniciando en el mundo de la bioinformática te recomendamos tomar el curso [Introducción a Bioinformática con Linux](https://github.com/landalab0/IntroduccionBioinformaticaLinux/tree/main) )

-Conocimientos básicos biológicos relacionados con biología molecular y ecología

## Archivos

-Para acceder a Amazon Web Services (AWS) consultar [Data Carpentry.](https://carpentries-lab.github.io/metagenomics-analysis/)

-Los datos usados en este taller provienen de tres muestras de Sedimento de Cuatro Ciénegas que puedes [descargar aquí.](https://zenodo.org/records/7010950):
